server:
  port: 8083

rocksdb:
  data-dir: block-data/node3

# tio 网络框架配置
tio:
  heart-timeout: 5000
  client-group-name: aizone-block-client
  server-group-context-name: aizone-block-server
  # 服务端监听的端口
  server-port: 7890
  # 服务端绑定的 IP
  server-ip: 127.0.0.1
  nodes:
    -
      ip: 127.0.0.1
      port: 5678
    -
      ip: 127.0.0.1
      port: 6789
    -
      ip: 127.0.0.1
      port: 7891
